---
id: toyamaburi2016
base_name: touch-of-ruby
tags: []
presentation_date: 2016/01/30
version: 0.0.1
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kunihiko Ito
  email: kuni.110.92@gmail.com
  rubygems_user: kunitoo
  slideshare_user: kunitoo
  speaker_deck_user: kunitoo
